### ISSUE TITLE
Android Basics: Persist data with Room - missing pictures

### ISSUE THREAD

**Issue by duemoselund** [google-developer-training/android-basics-kotlin-inventory-app#19]
The 'Before you Begin' page mentions an image of how Room fits in with the overall architecture recommended in the course, however, the image seems to no longer be available.

![image](https://user-images.githubusercontent.com/11139391/139226079-cfae4203-cba6-4b78-b712-2d5cdc90e654.png)

**Comment by calren** [comment]
This may have been a temporary error. Checking the current codelab (https://developer.android.com/codelabs/basic-android-kotlin-training-persisting-data-room), I'm able to see all the images. 

![Screen Shot 2021-11-02 at 2 23 30 PM](https://user-images.githubusercontent.com/5016806/139953768-8f30012b-fdfb-451a-b13a-f9c4ebd674a4.png)
