### ISSUE TITLE
Build Error fixed by change in app level build.gradle for Android Basics: Persist data with Room

### ISSUE THREAD

**Issue by mlnoone** [google-developer-training/android-basics-kotlin-inventory-app#21]
Changed in gradle this: kapt "androidx.room:room-compiler:$roomVersion" to this: annotationProcessor "androidx.room:room-compiler:$room_version"

**Comment by Andy-Cuong** [comment]
Thanks a lot, I encountered the same problem and your solution helped. There is another solution which is to change the room_version to 2.5.0-alpha02 and it worked, too. But since it is an alpha version there are probably bugs somewhere. It is good that I can stick with the stable version.
