### ISSUE TITLE
Android Basics: Persist data with Room

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-inventory-app#33]
ok, when I put the greater/minus sign on the right of Item, it turns red despite the fact it tells me to do so in the tutorial.

it says when I hover the mouse over it...." No type arguments expected for class Flow"

how can it be wrong AND right at the same time?

screen shots below..

<img width="1440" alt="Screen Shot 2022-02-18 at 1 08 50 PM" src="https://user-images.githubusercontent.com/91148652/154746855-7bf2f5fd-63f1-47a0-9ae3-b3108de68c49.png">

<img width="1440" alt="Screen Shot 2022-02-18 at 1 09 18 PM" src="https://user-images.githubusercontent.com/91148652/154746865-5d013821-2517-4373-b52b-4e93eafc6b4a.png">

**Comment by Gui88** [comment]
You're using the wrong import. 
Replace `import java.util.concurrent.Flow` with `import kotlinx.coroutines.flow.Flow`

**Comment by jh115424** [comment]
thanks!

oh, I sent in an issue on the Lunchbox app on the issues list.

It is the 1st one, so you should see it.

thanks,



Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:9533d675-53fe-4162-8a11-602da49bddf0]<https://your.tradeinvalet.com/tdhe0j>

________________________________

**Comment by skatingtamara** [comment]
@Gui88 Thanks! Your solution helped me as well. @jh115424, thanks for posting. Much appreciated!

**Comment by dogtim** [comment]
@Gui88 Thanks a lot! Appreciate your posting :heart_eyes:

**Comment by jh115424** [comment]
What are you talking about?    I needed help with it.   It wasn't a suggestion.

Anyway.   That is old, I got the answer on that long time ago.



I posted a NEW issue yesterday  with the Dogglers App.

Please check it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
