### ISSUE TITLE
Facing this issue- "Type of the parameter must be a class annotated with @Entity" 

### ISSUE THREAD

**Issue by sourabhkumar47** [google-developer-training/android-basics-kotlin-inventory-app#52]
**In which task and step of the codelab can this issue be found?**

Inventory App code lab

**Describe the problem**

Showing error "Type of the parameter must be a class annotated with @Entity..." 

Solution -
Changed in Gradle from this:

`kapt "androidx.room:room-compiler:$roomVersion"`

to this:

`annotationProcessor "androidx.room:room-compiler:$room_version"`

or downgrade kotlin version.

**Comment by Sachin-Timilsina** [comment]
The other version is supposed to be for Java not **kotlin**!
