### ISSUE TITLE
Android Basics: Persist data with Room

### ISSUE THREAD

**Issue by vexijio** [google-developer-training/android-basics-kotlin-inventory-app#79]
I'm not sure, if the code on step 4 is correct - "override fun <T : ViewModel?> create(modelClass: Class<T>): T {TODO("Not yet implemented")}". There is no such method defined that takes nullable 'ViewModel?'. According to documentation, Factory interface has public fun <T : ViewModel> create(modelClass: Class<T>): T.

**Comment by operator22th** [comment]
Try this : override fun <T : ViewModel> create(modelClass: Class): T {TODO("Not yet implemented")}

**Comment by vexijio** [comment]
> Try this : override fun create(modelClass: Class): T {TODO("Not yet implemented")}

Yes, i did back then, but still it should be updated in the training i think
